### ISSUE TITLE
numParts = int(os.environ['DECODED_PARTS'])

### ISSUE THREAD

**Issue by gm232425** [chinaworker/raspberry-sms#1]
Traceback (most recent call last):
  File "smsForward.py", line 15, in <module>
    numParts = int(os.environ['DECODED_PARTS'])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DECODED_PARTS'
 这个变量怎么回事
系统乌班图20.04

**Comment by chinaworker** [comment]
你这是手动执行py代码，不可以手动执行的。你按照步骤一步一步操作就可以功能实现
